# Generated by Django 4.2.6 on 2023-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('img_url', models.TextField()),
                ('list_ingredient', models.ManyToManyField(to='Ingredient.ingredient')),
            ],
        ),
    ]
