# Generated by Django 4.2.7 on 2023-11-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0002_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
