# Generated by Django 4.2.6 on 2023-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredient', '0003_remove_dish_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fibre',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='protein',
        ),
        migrations.AddField(
            model_name='dish',
            name='carbs',
            field=models.CharField(default=1, help_text='Enter carbohydrate content per 100 g', max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.CharField(default=1, help_text='Enter fat content per 100 g', max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.CharField(default=1, help_text='Enter protein content per 100 g', max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
